### ISSUE TITLE
Site does not work anymore on Chrome

### ISSUE THREAD

**Issue by Freezard** [Raylehnhoff/Have-I-Cubed-This-Yet#10]
items.js?v=20150310:408 Uncaught TypeError: masterList[i] is not a function

If you visit the site and then refresh without doing anything it will be broken forever and I guess the only way of repairing it is clearing local storage.

**Comment by Raylehnhoff** [comment]
I have a fix for this out on the test site, along with season 5 migrations:
http://raylehnhoff.github.io/HICTY-Test

**Comment by Freezard** [comment]
OK, good to know :) Will you apply the new stuff to the real site soon?

**Comment by Raylehnhoff** [comment]
Probably this evening, yes.

**Comment by Raylehnhoff** [comment]
This should be resolved as of the most recent commit.
