### ISSUE TITLE
Page does not work after reload, empty content is loaded

### ISSUE THREAD

**Issue by prusswan** [Raylehnhoff/Have-I-Cubed-This-Yet#9]

**Comment by Raylehnhoff** [comment]
What was the issue? Is it resolved for you?

**Comment by prusswan** [comment]
Issue seems to be caused by github.io, so I closed it.

**Comment by Raylehnhoff** [comment]
This is the first I've heard of it. Sometimes people running https anywhere
can have issues with sites like this. Could that be the case for you?

**Comment by prusswan** [comment]
I ran into it again on Opera and Chrome (https://raylehnhoff.github.io/Have-I-Cubed-This-Yet/)

The console error looks something like:

> items.js?v=20150310:408 Uncaught TypeError: masterList[i] is not a functionSite._checkConsistencyAndSort @ items.js?v=20150310:408Site.checkConsistency @ items.js?v=20150310:452Site.init @ items.js?v=20150310:195(anonymous function) @ footerScripts.js:5j @ jquery-1.11.3.min.js:2k.fireWith @ jquery-1.11.3.min.js:2m.extend.ready @ jquery-1.11.3.min.js:2J @ jquery-1.11.3.min.js:2

**Comment by Raylehnhoff** [comment]
This site uses hard-coded HTTP paths, so a https:// url will cause some
files to not load. It's probably an oversight, but there's no data
transmission, so no need for https.
